version: '3.8'

services:
  db_neulpoom_user:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: neulpoom_user
    ports:
      - "3307:3306"
    volumes:
      - db_user:/var/lib/mysql
      - ./mysql-init/user:/docker-entrypoint-initdb.d
    restart: always
    networks:
      - neulpoom_network

  db_neulpoom_lecture:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: neulpoom_lecture
    ports:
      - "3308:3306"
    volumes:
      - db_lecture:/var/lib/mysql
      - ./mysql-init/lecture:/docker-entrypoint-initdb.d
    restart: always
    networks:
      - neulpoom_network

  db_neulpoom_coupon:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: neulpoom_coupon
    ports:
      - "3309:3306"
    volumes:
      - db_coupon:/var/lib/mysql
      - ./mysql-init/coupon:/docker-entrypoint-initdb.d
    restart: always
    networks:
      - neulpoom_network

  db_neulpoom_payment:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: neulpoom_payment
    ports:
      - "3310:3306"
    volumes:
      - db_payment:/var/lib/mysql
      - ./mysql-init/payment:/docker-entrypoint-initdb.d
    restart: always
    networks:
      - neulpoom_network

  db_neulpoom_lecture_resource:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: neulpoom_lecture_resource
    ports:
      - "3311:3306"
    volumes:
      - db_lecture_resource:/var/lib/mysql
      - ./mysql-init/lecture_resource:/docker-entrypoint-initdb.d
    restart: always
    networks:
      - neulpoom_network

  db_neulpoom_order:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: neulpoom_order
    ports:
      - "3312:3306"
    volumes:
      - db_order:/var/lib/mysql
      - ./mysql-init/order:/docker-entrypoint-initdb.d
    restart: always
    networks:
      - neulpoom_network

  redis_user:
    hostname: redis_user
    container_name: redis_user
    image: redis:6
    ports:
      - "6381:6379"
    networks:
      - neulpoom_network

  redis_coupon:
    hostname: redis_coupon
    container_name: redis_coupon
    image: redis:6
    ports:
      - "6380:6379"
    networks:
      - neulpoom_network

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.6.0
    container_name: es_lecture
    ports:
      - "9200:9200"
    environment:
      - node.name=es_lecture
      - discovery.type=single-node
      - xpack.security.enabled=false
    networks:
      - neulpoom_network
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - es_data:/usr/share/elasticsearch/data

  kibana:
    image: docker.elastic.co/kibana/kibana:8.6.0
    container_name: kibana_lecture
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    networks:
      - neulpoom_network
    depends_on:
      - elasticsearch

volumes:
  db_user:
  db_lecture:
  db_coupon:
  db_payment:
  db_lecture_resource:
  db_order:
  es_data:
    driver: local

networks:
  neulpoom_network: